In [6]:
import numpy as np

np.random.seed(85)

lotto_results = []

# 3회 실행
for _ in range(3):
    a = np.arange(1, 46)  # 1부터 45까지 배열 생성
    np.random.shuffle(a)  # 배열 섞기
    lotto = a[:6]  # 처음 6개의 숫자 선택
    lotto_results.append(list(lotto))  # 리스트에 추가

# 2차원 배열로 변환
lotto_array = np.array(lotto_results)

# 결과 출력
print(lotto_array)


[[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]]
