In [1]:
import numpy as np

# 3차원 배열의 크기를 지정합니다.
shape = (3, 4, 5)

# 3차원 배열을 생성합니다.
arr = np.random.randint(0, 10, shape)

# 3차원 배열을 출력합니다.
print(arr)


[[[1 7 9 4 7]
  [3 0 4 7 6]
  [9 7 6 6 7]
  [5 0 1 5 4]]

 [[8 4 7 4 7]
  [7 1 2 6 7]
  [4 3 1 2 0]
  [7 5 3 6 0]]

 [[0 7 3 3 4]
  [8 9 1 6 2]
  [9 0 1 4 8]
  [5 5 7 9 7]]]


In [2]:
import numpy as np

# 1. Shape가 (3, 3, 6)이고, 원소가 0~20 사이의 정수를 갖는 3차원 배열 생성
array_3d = np.random.randint(0, 21, (3, 3, 6))

# 2. Shape가 (5, 6)이고, 원소가 0~100 사이의 정수를 갖는 2차원 배열 생성
array_2d = np.random.randint(0, 101, (5, 6))

# 배열 출력
print("3차원 배열:")
print(array_3d)

print("\n2차원 배열:")
print(array_2d)


3차원 배열:
[[[18 16 17  1 10  9]
  [ 9 16  4  1 12  2]
  [19 11  1 14  9 19]]

 [[18  0  3  9  6  4]
  [19  2 10 17  5  2]
  [16 16 10  8  6  5]]

 [[ 2  8  5  9  2 11]
  [14  2  2  3 18 20]
  [19  6 20  5 14  6]]]

2차원 배열:
[[ 4 38 58 71 21 43]
 [80 64 57 12 81 46]
 [54 79 10 13 74 14]
 [36 47 21 75 18 69]
 [90 95 53 26 63 26]]


In [3]:
import numpy as np

# 1차원 배열 생성
temp = np.arange(48)

# 1. reshape 메서드를 활용하여 (4, 3, 4) 크기의 3차원 배열 생성
array_3d = temp.reshape((4, 3, 4))

# 2. reshape 메서드를 활용하여 (6, 8) 크기의 2차원 배열 생성
array_2d = temp.reshape((6, 8))

# 배열 출력
print("3차원 배열 (4, 3, 4):")
print(array_3d)

print("\n2차원 배열 (6, 8):")
print(array_2d)



3차원 배열 (4, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

2차원 배열 (6, 8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
